# Generated by Django 6.0.1 on 2026-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='hero_image/')),
                ('is_active', models.BooleanField(default=True)),
                ('mph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_range', models.PositiveIntegerField()),
                ('peak_hp', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
            },
        ),
    ]
