# Generated by Django 6.0.1 on 2026-02-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='car_range',
        ),
        migrations.RemoveField(
            model_name='design',
            name='mph',
        ),
        migrations.RemoveField(
            model_name='design',
            name='peak_hp',
        ),
    ]
