# Generated by Django 6.0.1 on 2026-02-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mileage_km',
            new_name='odometer_reading',
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
